### PR TITLE
Migration from tslint to eslint

### PR DESCRIPTION
**Pull request by psyycker**
Tslint is going to be deprecated. Just migrated the project to eslint and fixed the files based on almost the same configuration as before.

### CODE REVIEW

**Comment by Robinfr** [comment]
Seems good, will check it out! (I somehow completely missed this).

**Comment by Robinfr** [comment]
Based on your MR I've created a branch for this. Check out the `eslint` branch and let me know what you think. I want to play around with it a bit more to make sure I'm happy with the rules before I merge it.

**Comment by Robinfr** [comment]
OK, I'm happy with the rules for now I think. If you have time, check it out, otherwise I'll most likely merge it this weekend.

**Comment by maury91** [comment]
Hello there,

I tried the eslint branch, currently, eslint fails due to the rule `import/extensions`.

I suggest adding to `.eslintrc.json`.`rules`;
```json
    "import/extensions": 0,
```

here are the errors without that rule:

```
$ eslint --ext=jsx,js,tsx,ts src

/Users/mauriziocarboni/development/onetime/webpage-analysis-tool/src/renderer/actions/index.ts
  1:31  error  Missing file extension "ts" for "./counterActions"  import/extensions

/Users/mauriziocarboni/development/onetime/webpage-analysis-tool/src/renderer/app.tsx
  6:25  error  Missing file extension "tsx" for "./components/Application"  import/extensions
  7:19  error  Missing file extension "ts" for "./store"                    import/extensions

/Users/mauriziocarboni/development/onetime/webpage-analysis-tool/src/renderer/components/Application.tsx
  1:21  error  Missing file extension "ts" for "react-hot-loader/root"           import/extensions
  4:30  error  Missing file extension "ts" for "../containers/CounterContainer"  import/extensions

/Users/mauriziocarboni/development/onetime/webpage-analysis-tool/src/renderer/containers/CounterContainer.ts
  4:21  error  Missing file extension "tsx" for "../components/Counter"     import/extensions
  5:27  error  Missing file extension "ts" for "../reducers"                import/extensions
  6:53  error  Missing file extension "ts" for "../actions/counterActions"  import/extensions

/Users/mauriziocarboni/development/onetime/webpage-analysis-tool/src/renderer/reducers/counterReducer.ts
  3:53  error  Missing file extension "ts" for "../actions/counterActions"  import/extensions

/Users/mauriziocarboni/development/onetime/webpage-analysis-tool/src/renderer/reducers/index.ts
  3:46  error  Missing file extension "ts" for "./counterReducer"  import/extensions

/Users/mauriziocarboni/development/onetime/webpage-analysis-tool/src/renderer/store/index.ts
  4:40  error  Missing file extension "ts" for "../reducers"  import/extensions

✖ 11 problems (11 errors, 0 warnings)

error Command failed with exit code 1.
```

it can also be fixed by being specific about the extensions in the import.

**Comment by Robinfr** [comment]
@maury91 you're probably not using the package-lock file in that case since the version in there does not have that problem. 

Anyway, I've updated the dependencies and added the config you mentioned so should be fine now! Thanks for trying out the eslint branch! Let me know if you prefer it over the tslint branch so I can make it the default in the future.

**Comment by kevinlabx** [comment]
@Robinfr 
Hey, Thank you for the templates. Coming from JS to TS had to overcome a couple things. You're template helped out in few parts.

Just letting you know `TSlint` is deprecated. 

image

You should migrate this to ESLint with TSLint plugins
https://github.com/typescript-eslint/typescript-eslint

Here is an official response from `ESLint` team regarding that project.
https://eslint.org/blog/2019/01/future-typescript-eslint#top

Wish you the best. 👍

**Comment by Robinfr** [comment]
@kevinlabx thanks for your comment, you can use the `eslint` branch for now if you want to use ESLint. I'm just waiting for the ESLint environment to become a bit more stable before switching to it permanently. But don't let yourself be stopped by that, the eslint branch works just fine!

**Comment by kevinlabx** [comment]
@Robinfr 
I am currently using ESLint with TS plugins and I have not run into any issues yet. I will let you know if I run into an issue for using ESLint on our project for TS. 🙂

**Comment by Robinfr** [comment]
ESLint is now in master #21 

If you want to still use tslint you can use the `tslint` branch.

**Pull request closed without merging**
